a = (input('Digite algo: '))
print('O tipo primitivo é ', type(a))
print('So tem espaços?',a.isspace())
print('So tem numeros?', a.isnumeric())
print('É alfabetico?',a.isalpha())
print('Tem letras e numeros', a.isalnum()) 
print('Esta em maiusculas?', a.isupper())
print('Esta em minusculas?', a.islower())
print('Esta capitalizada?', a.istitle)