a = str(input('Digite seu nome: ')).strip()
print('Analisando seu nome...')
b = a.upper()
c = a.lower()
d = len(a) - a.count(' ')
e = a.find(' ')

print('Seu nome em maiusculas é {}'.format(b))
print('Seu nome em minusculas é {}'.format(c))
print('Seu nome tem {} letras' .format(d))
print('Seu primeiro nome tem {} letras'.format(e))